### ISSUE TITLE
Ubuntu 20.04: A fatal error occurred. The required library libhostfxr.so could not be found.

### ISSUE THREAD

**Issue by tolik518** [Andrew-Eathan/pngsmasher#1]
Using the pngsmasher v2.1 with the linux-x64 build I ran the command at the bottom and got the following exception at the bottom. 
It looks like libhostfxr.so isn't shipped with the binary.

```bash
./pngsmasher.cli -input pslogo.png -output pngsmasher_logo.png -splits 6 -regions 2 -splitmin 20 -crunch 80 -seed 10 -frames 30 -fps 10 +grayabb -grayabbwidth 2 -grayabbpower 0.75 +bg -bgred 0 -bggreen 0 -bgblue 0 +ntsc -fringe 1 -breaks 30
```
```
A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/home/developer/Downloads/pngsmasher.cli-linux-x64/linux-x64/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet].

The .NET runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=ubuntu.20.04-x64&apphost_version=6.0.6
```

**Comment by Andrew-Eathan** [comment]
Hi, i read through the error, i'm fairly sure the linux builds of pngsmasher are framework-dependent.
Could you check if the .NET runtime is set up properly on your system? That error should only happen when the runtime isn't fully set up, since libhostfxr.so comes with the runtime. You can follow the instructions from the error message.

**Comment by tolik518** [comment]
Hey, ok so if it's framework dependent then it would make sense, I hoped it's a self-contained/framework-independed build.
Thank you :)

**Comment by Andrew-Eathan** [comment]
if you want, you could try compiling it to be self contained, though i might do that and add the binaries to the release at some point :)
